# Generated by Django 4.0.5 on 2022-06-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calc',
            name='Answer_Dwn',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='calc',
            name='Answer_Up',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
