# Generated by Django 4.0.5 on 2022-06-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0002_calc_answer_dwn_calc_answer_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='calc',
            name='user_id',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
